src/MonsterTraining/src/MonsterTraining/Controllers/GroupRegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using MonsterTraining.Models;
using Stripe;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MonsterTraining.Controllers
{
    public class GroupRegistrationController : Controller
    {
        private readonly StripeOptions _stripeOptions;

        public GroupRegistrationController(IOptions<StripeOptions> stripeOptions)
        {
            _stripeOptions = stripeOptions.Value;
        }

        public IActionResult Index(int minGroupSize = 5)
        {
            var groupSize = minGroupSize;
            if (groupSize < 3) groupSize = 3;

            ViewBag.MinGroupSize = groupSize;

            return View();
        }

        [HttpPost]
        public IActionResult Review(PreviewGroupRegistrationModel model)
        {
            // I ain't afraid of no ghosts
            var groupSize = model.GroupSize;
            if (groupSize < 3) groupSize = 3;            
            var total = (int)(1500 * groupSize);
            var gst = (int)(total * 0.05);

            var correctedAmountModel = new PreviewGroupRegistrationModel
            {
                EmailAddress = model.EmailAddress,
                ForgeryToken = model.ForgeryToken,
                FullName = model.FullName,
                Telephone = model.Telephone,
                GroupSize = groupSize,
                Gst = gst,
                Total = total,
                StripeAmount = (total + gst) * 100,
                Key = _stripeOptions.Key
            };
            
            
            return View(correctedAmountModel);
        }


        public IActionResult Complete(CompleteModel model)
        {

            StripeConfiguration.SetApiKey(_stripeOptions.SecretKey);

            var myCharge = new StripeChargeCreateOptions();

            // find the customer with stripe
            var customerService = new StripeCustomerService();
            var customer = customerService.List().FirstOrDefault(c => c.Email == model.EmailAddress);

            if (customer == null)
            {
                var newCustomer = new StripeCustomerCreateOptions
                {
                    Email = model.EmailAddress,
                    Description = model.FullName,
                    Metadata = new Dictionary<string, string>() {
                        { "Telephone", model.Telephone }
                    }                    
                };
                customer = customerService.Create(newCustomer);
            }

            // always set these properties
            var groupSize = model.GroupSize;
            if (groupSize < 3) groupSize = 3;
            var total = (int)(1500 * groupSize);
            var gst = (int)(total * 0.05);

            myCharge.Amount = (total + gst) * 100;
            myCharge.Currency = "cad";
            myCharge.Metadata = new Dictionary<string, string>()
            {
                {"CustomerId", customer.Id },
                {"CustomerEmail", model.EmailAddress }
            };

            // set this if you want to
            myCharge.Description = "ASP.NET Monsters Training";
            myCharge.Source = new StripeSourceOptions { TokenId = model.StripeToken };

            // (not required) set this to false if you don't want to capture the charge yet - requires you call capture later
            myCharge.Capture = true;

            var chargeService = new StripeChargeService();
            StripeCharge stripeCharge = chargeService.Create(myCharge);

            return View();
        }


    }
}

src/MonsterTraining/src/MonsterTraining/Views/GroupRegistration/Index.cshtml
@{
}

<div class="row ">
    <h2>Group Registration</h2>

    <p>
        Thanks for your interest in group rates for our workshop. If you've landed here off
        a link and would like more information about our content and itinerary, please be
        sure to check out our <a asp-controller="Home" asp-action="Index">landing page</a>
        for the complete course outline.
    </p>

    <hr />

    <h3>Who's Leading Your Crew?</h3>
    <p>
        We need a few details to complete the registration. Please let us know who will be
        the contact person for your group. 
    </p>
    <p>
        For group discounts, a minimum of 5 attendees is required.
    </p>    

    <form asp-controller="GroupRegistration" asp-action="Review" method="post">
        <div id="registration-form">
            <div class="row">
                <div class="medium-6 columns">
                    <label>
                        Group Contact Name
                        <input type="text" name="FullName" id="FullName" placeholder="Firsty McLastername">
                    </label>
                </div>
            </div>
            <div class="row">
                <div class="medium-6 columns">
                    <label>
                        Email Address
                        <input type="email" name="EmailAddress" id="EmailAddress" placeholder="foo@@ohsobar.com">
                    </label>
                </div>
            </div>
            <div class="row">
                <div class="medium-6 columns">
                    <label>
                        Phone Number
                        <input type="tel" name="Telephone" id="Telephone" placeholder="403-555-1234">
                    </label>
                </div>
            </div>

            <div class="row">
                <div class="medium-6 columns">
                    <label>
                        Number of Folks in Your Group
                    </label>
                    <div class="medium-9 columns">
                        <div class="slider" data-slider data-initial-start="5" data-start="@ViewBag.MinGroupSize" data-end="15" data-changed-delay="150">
                            <span class="slider-handle" data-slider-handle role="slider" tabindex="1" aria-controls="groupSize"></span>
                            <span class="slider-fill" data-slider-fill></span>
                        </div>
                    </div>
                    <div class="medium-3 columns">
                        <input type="number" name="GroupSize" id="groupSize">
                        <input type="hidden" name="Total" id="Total" />
                        <input type="hidden" name="Gst" id="Gst"/>
                        <input type="hidden" name="ForgeryToken" value="@Guid.NewGuid()" />
                        <input type="hidden" name="ForgeryDiscount" value="@Guid.NewGuid()" />
                        <input type="hidden" name="ForgeryRate" value="25" />
                    </div>
                </div>
            </div>
            
            <hr />

            <p>
                Your total will be <span style="font-weight:bold" id="total-amount">$</span> CAD, 
                including <span style="font-weight:bold" id="total-gst">$</span> GST.
            </p>

            <hr />

            <button type="submit" class="button success">Let's Do This.</button>

        </div>
    </form>


</div>

@section Scripts{

<script type="text/javascript">

    $(function () {

        $('.slider').on('changed.zf.slider', function(){

            var class_size = $(this).children('.slider-handle').attr('aria-valuenow');
            var total = parseInt(class_size) * 1500;
            var gst = 0.05 * (total);
            
            $("#total-gst").html("$" + gst);
            $("#total-amount").html("$" + (gst + total));

            $('#Total').val(total);
            $('#Gst').val(gst);

        });
    });

</script>
    
}

src/MonsterTraining/src/MonsterTraining/Views/GroupRegistration/Review.cshtml
@model PreviewGroupRegistrationModel

<div class="row">

    <h3>Did We Get That Right?</h3>
    <p>
        Please review the information below, and if you 
        are all set, click the magic button at the bottom 
        of the form and get set to join us at the workshop.
        It'll be #swellacool.
    </p>
    
    <hr />

    <table>
        <thead>
            <tr>
                <th colspan="2">Summary of Awesome</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Contact Name</td>
                <td>@Model.FullName</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>@Model.EmailAddress</td>
            </tr>
            <tr>
                <td>Phone Number</td>
                <td>@Model.Telephone</td>
            </tr>
            <tr>
                <td>Group Size</td>
                <td>@Model.GroupSize</td>
            </tr>
            <tr>
                <td>Total (Including GST)</td>
                <td>$@(Model.Total + Model.Gst)</td>
            </tr>
        </tbody>
    </table>
    
    <hr />

    <div class="callout">
        <ul class="menu simple">
            <li>Engage ASP.NET Core Warp Drive...</li>
            <li>
                <form action="/GroupRegistration/Complete" method="POST">
                    <input type="hidden" name="GroupSize" value="@Model.GroupSize" />
                    <input type="hidden" name="StripeAmount" value="@Model.StripeAmount" />
                    <input type="hidden" name="EmailAddress" value="@Model.EmailAddress" />
                    <input type="hidden" name="Telephone" value="@Model.Telephone" />
                    <input type="hidden" name="FullName" value="@Model.FullName" />
                    <input type="hidden" name="ForgeryToken" value="@Model.ForgeryToken" />

                    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                            data-key="@Model.Key"
                            data-amount="@Model.StripeAmount"
                            data-name="ASP.NET Monsters"
                            data-description="Calgary ASP.NET Core Training"
                            data-image="/images/small_logo.png"
                            data-locale="auto"
                            data-billing-address="true"
                            data-currency="cad"
                            data-zip-code="true"
                            data-label="Sign up for the Calgary class">
                    </script>

                </form>
            </li>
        </ul>
    </div>

</div>